import type { IntakeLang } from "./intake-lang";

const FR: Record<string, string> = {
  "s2.e": "Étape 02",
  "s2.t": "Votre voyage",
  "s2.tripTypes": "Type de voyage (plusieurs choix)",
  "s2.travelers": "Nombre de voyageurs",
  "s2.duration": "Durée",
  "s2.days": "jours",
  "s2.dates": "Dates souhaitées",
  "s2.period": "Période souhaitée",
  "s2.regions": "Régions d’intérêt",
  "s2.flex": "Dates flexibles",
  "s2.choose": "— Choisir —",
  "s2.tl1": "Voyageur solo",
  "s2.tl2": "Couple",
  "s2.tl3": "Petit groupe ({n})",
  "s2.tl4": "Groupe ({n})",
  "s3.e": "Étape 03",
  "s3.t": "Budget & hébergement",
  "s3.budget": "Budget par personne",
  "s3.acc": "Style d’hébergement",
  "s3.amen": "Indispensables",
  "s4.e": "Étape 04",
  "s4.t": "Expériences & goûts",
  "s4.act": "Activités",
  "s4.dining": "Restauration",
  "s4.pace": "Rythme",
  "s5.e": "Étape 05",
  "s5.t": "Santé & logistique",
  "s5.diet": "Restrictions alimentaires (optionnel)",
  "s5.med": "Santé / mobilité (optionnel)",
  "s5.ins": "Assurance voyage",
  "s5.visa": "Visa / passeport",
  "s5.visaD": "Précisez votre passeport",
  "s5.flights": "Vols réservés ?",
  "s5.confidential": "Cette information reste confidentielle et nous aide à adapter votre itinéraire.",
  "s6.e": "Étape 06",
  "s6.t": "Touche finale",
  "s6.rank": "Classez vos priorités (les 3 premières comptent le plus)",
  "s6.free": "Autre chose à nous dire ?",
  "s6.ref": "Comment nous avez-vous connus ?",
  "s6.placeholder": "Un anniversaire à fêter ? Une phobie ? Un rêve à réaliser ?",
  "s6.mkt": "Je souhaite recevoir des idées de voyage et inspirations par email (optionnel).",
  "s6.consentStart": "J'accepte que mes données soient utilisées pour personnaliser mon voyage.",
  "s6.privacy": "Politique de confidentialité",
  "s7.e": "Étape 07",
  "s7.t": "Vos vols internationaux",
  "s7.intro": "Si vous avez déjà réservé vos vols, partagez les détails pour que nous organisions vos transferts.",
  "s7.opt": "Tous les champs sont facultatifs.",
  "s7.arr": "Arrivée en Colombie",
  "s7.dep": "Départ de Colombie",
  "s7.airline": "Compagnie",
  "s7.fn": "N° de vol",
  "s7.date": "Date",
  "s7.arrT": "Heure d'arrivée",
  "s7.depT": "Heure de départ",
  "s7.cityArr": "Ville / aéroport d'arrivée",
  "s7.cityDep": "Ville / aéroport de départ",
};

const EN: Record<string, string> = {
  "s2.e": "Step 02",
  "s2.t": "Your trip",
  "s2.tripTypes": "Trip type (multiple choices)",
  "s2.travelers": "Number of travelers",
  "s2.duration": "Duration",
  "s2.days": "days",
  "s2.dates": "Preferred dates",
  "s2.period": "Preferred season",
  "s2.regions": "Regions of interest",
  "s2.flex": "Flexible dates",
  "s2.choose": "— Choose —",
  "s2.tl1": "Solo traveler",
  "s2.tl2": "Couple",
  "s2.tl3": "Small group ({n})",
  "s2.tl4": "Group ({n})",
  "s3.e": "Step 03",
  "s3.t": "Budget & lodging",
  "s3.budget": "Budget per person",
  "s3.acc": "Lodging style",
  "s3.amen": "Must-haves",
  "s4.e": "Step 04",
  "s4.t": "Experiences & tastes",
  "s4.act": "Activities",
  "s4.dining": "Dining",
  "s4.pace": "Pace",
  "s5.e": "Step 05",
  "s5.t": "Health & logistics",
  "s5.diet": "Dietary restrictions (optional)",
  "s5.med": "Health / mobility (optional)",
  "s5.ins": "Travel insurance",
  "s5.visa": "Visa / passport",
  "s5.visaD": "Please specify your passport",
  "s5.flights": "Flights already booked?",
  "s5.confidential": "This stays confidential and helps us adapt your itinerary.",
  "s6.e": "Step 06",
  "s6.t": "Final touches",
  "s6.rank": "Rank your priorities (top 3 matter most)",
  "s6.free": "Anything else we should know?",
  "s6.ref": "How did you hear about us?",
  "s6.placeholder": "A birthday to celebrate? A fear? A dream?",
  "s6.mkt": "I’d like travel ideas and inspiration by email (optional).",
  "s6.consentStart": "I agree that my data may be used to personalize my trip.",
  "s6.privacy": "Privacy policy",
  "s7.e": "Step 07",
  "s7.t": "Your international flights",
  "s7.intro": "If you’ve already booked flights, share the details so we can arrange airport transfers.",
  "s7.opt": "All fields are optional.",
  "s7.arr": "Arrival in Colombia",
  "s7.dep": "Departure from Colombia",
  "s7.airline": "Airline",
  "s7.fn": "Flight no.",
  "s7.date": "Date",
  "s7.arrT": "Arrival time",
  "s7.depT": "Departure time",
  "s7.cityArr": "Arrival city / airport",
  "s7.cityDep": "Departure city / airport",
};

const ES: Record<string, string> = {
  "s2.e": "Paso 02",
  "s2.t": "Su viaje",
  "s2.tripTypes": "Tipo de viaje (varias opciones)",
  "s2.travelers": "Número de viajeros",
  "s2.duration": "Duración",
  "s2.days": "días",
  "s2.dates": "Fechas deseadas",
  "s2.period": "Temporada deseada",
  "s2.regions": "Regiones de interés",
  "s2.flex": "Fechas flexibles",
  "s2.choose": "— Elegir —",
  "s2.tl1": "Viajero solo",
  "s2.tl2": "Pareja",
  "s2.tl3": "Grupo pequeño ({n})",
  "s2.tl4": "Grupo ({n})",
  "s3.e": "Paso 03",
  "s3.t": "Presupuesto y alojamiento",
  "s3.budget": "Presupuesto por persona",
  "s3.acc": "Estilo de alojamiento",
  "s3.amen": "Imprescindibles",
  "s4.e": "Paso 04",
  "s4.t": "Experiencias y gustos",
  "s4.act": "Actividades",
  "s4.dining": "Restauración",
  "s4.pace": "Ritmo",
  "s5.e": "Paso 05",
  "s5.t": "Salud y logística",
  "s5.diet": "Restricciones alimentarias (opcional)",
  "s5.med": "Salud / movilidad (opcional)",
  "s5.ins": "Seguro de viaje",
  "s5.visa": "Visa / pasaporte",
  "s5.visaD": "Precise su pasaporte",
  "s5.flights": "¿Vuelos ya reservados?",
  "s5.confidential": "Esta información es confidencial y nos ayuda a adaptar su itinerario.",
  "s6.e": "Paso 06",
  "s6.t": "Toque final",
  "s6.rank": "Ordene sus prioridades (las 3 primeras pesan más)",
  "s6.free": "¿Algo más que debamos saber?",
  "s6.ref": "¿Cómo nos conoció?",
  "s6.placeholder": "¿Un cumpleaños? ¿Un miedo? ¿Un sueño?",
  "s6.mkt": "Deseo recibir ideas e inspiración de viaje por email (opcional).",
  "s6.consentStart": "Acepto que mis datos se usen para personalizar mi viaje.",
  "s6.privacy": "Política de privacidad",
  "s7.e": "Paso 07",
  "s7.t": "Sus vuelos internacionales",
  "s7.intro": "Si ya reservó vuelos, comparta los detalles para organizar los traslados al aeropuerto.",
  "s7.opt": "Todos los campos son opcionales.",
  "s7.arr": "Llegada a Colombia",
  "s7.dep": "Salida de Colombia",
  "s7.airline": "Aerolínea",
  "s7.fn": "Nº de vuelo",
  "s7.date": "Fecha",
  "s7.arrT": "Hora de llegada",
  "s7.depT": "Hora de salida",
  "s7.cityArr": "Ciudad / aeropuerto de llegada",
  "s7.cityDep": "Ciudad / aeropuerto de salida",
};

const DE: Record<string, string> = {
  "s2.e": "Schritt 02",
  "s2.t": "Ihre Reise",
  "s2.tripTypes": "Reiseart (mehrere möglich)",
  "s2.travelers": "Anzahl Reisende",
  "s2.duration": "Dauer",
  "s2.days": "Tage",
  "s2.dates": "Gewünschte Daten",
  "s2.period": "Gewünschte Saison",
  "s2.regions": "Interessante Regionen",
  "s2.flex": "Flexible Daten",
  "s2.choose": "— Wählen —",
  "s2.tl1": "Alleinreisende(r)",
  "s2.tl2": "Paar",
  "s2.tl3": "Kleine Gruppe ({n})",
  "s2.tl4": "Gruppe ({n})",
  "s3.e": "Schritt 03",
  "s3.t": "Budget & Unterkunft",
  "s3.budget": "Budget pro Person",
  "s3.acc": "Unterkunftsstil",
  "s3.amen": "Must-haves",
  "s4.e": "Schritt 04",
  "s4.t": "Erlebnisse & Vorlieben",
  "s4.act": "Aktivitäten",
  "s4.dining": "Gastronomie",
  "s4.pace": "Tempo",
  "s5.e": "Schritt 05",
  "s5.t": "Gesundheit & Logistik",
  "s5.diet": "Ernährungseinschränkungen (optional)",
  "s5.med": "Gesundheit / Mobilität (optional)",
  "s5.ins": "Reiseversicherung",
  "s5.visa": "Visum / Reisepass",
  "s5.visaD": "Bitte Reisepass präzisieren",
  "s5.flights": "Flüge bereits gebucht?",
  "s5.confidential": "Diese Angaben sind vertraulich und helfen uns, Ihre Route anzupassen.",
  "s6.e": "Schritt 06",
  "s6.t": "Letzte Details",
  "s6.rank": "Prioritäten sortieren (Top 3 zählen am meisten)",
  "s6.free": "Noch etwas, das wir wissen sollten?",
  "s6.ref": "Wie haben Sie von uns erfahren?",
  "s6.placeholder": "Geburtstag? Eine Angst? Ein Traum?",
  "s6.mkt": "Ich möchte Reiseideen und Inspiration per E-Mail (optional).",
  "s6.consentStart": "Ich stimme zu, dass meine Daten zur Personalisierung meiner Reise genutzt werden.",
  "s6.privacy": "Datenschutz",
  "s7.e": "Schritt 07",
  "s7.t": "Ihre internationalen Flüge",
  "s7.intro": "Wenn Sie bereits Flüge gebucht haben, teilen Sie die Details für Flughafentransfers.",
  "s7.opt": "Alle Felder sind optional.",
  "s7.arr": "Ankunft in Kolumbien",
  "s7.dep": "Abflug aus Kolumbien",
  "s7.airline": "Airline",
  "s7.fn": "Flugnr.",
  "s7.date": "Datum",
  "s7.arrT": "Ankunftszeit",
  "s7.depT": "Abflugzeit",
  "s7.cityArr": "Ankunftsstadt / Flughafen",
  "s7.cityDep": "Abflugstadt / Flughafen",
};

const MAP: Record<IntakeLang, Record<string, string>> = { fr: FR, en: EN, es: ES, de: DE };

export function intakeField(lang: IntakeLang, key: string): string {
  return MAP[lang][key] ?? FR[key] ?? key;
}

export function travelerSummaryLabel(lang: IntakeLang, n: number): string {
  if (n === 1) return intakeField(lang, "s2.tl1");
  if (n === 2) return intakeField(lang, "s2.tl2");
  if (n <= 6) return intakeField(lang, "s2.tl3").replace("{n}", String(n));
  return intakeField(lang, "s2.tl4").replace("{n}", String(n));
}
