import type { z } from "zod";
import type { IntakeLang } from "./intake-lang";
import { intakeFullSchema } from "./schema";

/** Flat UI strings for intake (not admin). Fallback chain: lang → fr → key. */
const STRINGS: Record<IntakeLang, Record<string, string>> = {
  fr: {
    "progress.1": "Étape 1 sur 7 — Vos coordonnées",
    "progress.2": "Étape 2 sur 7 — Votre voyage",
    "progress.3": "Étape 3 sur 7 — Budget & hébergement",
    "progress.4": "Étape 4 sur 7 — Expériences & intérêts",
    "progress.5": "Étape 5 sur 7 — Santé & logistique",
    "progress.6": "Étape 6 sur 7 — Touche finale",
    "progress.7": "Étape 7 sur 7 — Vos vols internationaux",
    "progress.review": "Révision — vérifiez vos réponses",
    "progress.done": "Merci !",
    "header.title": "Racontez-nous votre voyage de rêve",
    "header.sub": "Quelques questions pour créer une expérience qui vous ressemble. Comptez environ 4 minutes.",
    "nav.prev": "← Précédent",
    "nav.next": "Suivant →",
    "nav.recap": "Voir le récapitulatif",
    "nav.editReview": "← Modifier",
    "nav.submit": "Confirmer et envoyer ✨",
    "nav.sending": "Envoi…",
    "review.title": "Récapitulatif",
    "review.contact": "Coordonnées",
    "review.trip": "Voyage",
    "review.budget": "Budget & hébergement",
    "review.exp": "Expériences",
    "review.health": "Santé & logistique",
    "review.final": "Touche finale",
    "review.flights": "Vols internationaux",
    "review.edit": "Modifier",
    "done.line1": "Votre concierge va préparer quelque chose d'exceptionnel. 🇨🇴",
    "done.line2": "🕐 Réponse sous 24 – 48 h",
    "errors.fields": "Vérifiez les champs en surbrillance.",
    "errors.submitIncomplete": "Certaines réponses sont incomplètes. Retournez aux étapes concernées.",
    "errors.submitFailed": "Envoi impossible. Réessayez.",
    "errors.network": "Réseau indisponible.",
    "done.title": "Merci {name} !",
    "review.tripLine": "{n} voyageur(s), {d} jours",
    "flight.sep": " · ",
    "flight.arr": "Arrivée",
    "flight.dep": "Départ",
    "flight.noneShort": "Non renseigné — facultatif.",
    "flight.noneLong": "Non renseigné — facultatif, pour vos transferts aéroport.",
    "step1.eyebrow": "Étape 01",
    "step1.title": "Faisons connaissance",
    "step1.docsLang": "Dans quelle langue souhaitez-vous recevoir vos documents ?",
    "step1.docsLangSub": "In which language would you like to receive your documents?",
    "step1.spoken": "Quelles langues parlez-vous ?",
    "step1.spokenSub": "What languages do you speak?",
    "step1.guide": "Pour vos visites guidées, quelle langue préférez-vous ?",
    "step1.guideSub": "For guided visits, what language do you prefer?",
    "step1.guideHelp": "Selon les régions visitées, nous ferons notre possible pour vous proposer un guide dans cette langue.",
    "step1.name": "Votre nom complet",
    "step1.email": "Adresse email",
    "step1.phone": "Téléphone / WhatsApp",
    "step1.contactPref": "Comment préférez-vous être contacté(e) ?",
  },
  en: {
    "progress.1": "Step 1 of 7 — Your details",
    "progress.2": "Step 2 of 7 — Your trip",
    "progress.3": "Step 3 of 7 — Budget & lodging",
    "progress.4": "Step 4 of 7 — Experiences & interests",
    "progress.5": "Step 5 of 7 — Health & logistics",
    "progress.6": "Step 6 of 7 — Final touches",
    "progress.7": "Step 7 of 7 — Your international flights",
    "progress.review": "Review — check your answers",
    "progress.done": "Thank you!",
    "header.title": "Tell us about your dream trip",
    "header.sub": "A few questions to shape an experience that fits you. About 4 minutes.",
    "nav.prev": "← Back",
    "nav.next": "Next →",
    "nav.recap": "View summary",
    "nav.editReview": "← Edit",
    "nav.submit": "Confirm and send ✨",
    "nav.sending": "Sending…",
    "review.title": "Summary",
    "review.contact": "Contact details",
    "review.trip": "Trip",
    "review.budget": "Budget & lodging",
    "review.exp": "Experiences",
    "review.health": "Health & logistics",
    "review.final": "Final touches",
    "review.flights": "International flights",
    "review.edit": "Edit",
    "done.line1": "Your concierge will prepare something exceptional for you. 🇨🇴",
    "done.line2": "🕐 We’ll reply within 24–48 h",
    "errors.fields": "Please check the highlighted fields.",
    "errors.submitIncomplete": "Some answers are incomplete. Go back to the relevant steps.",
    "errors.submitFailed": "Could not send. Please try again.",
    "errors.network": "Network unavailable.",
    "done.title": "Thank you, {name}!",
    "review.tripLine": "{n} travelers, {d} days",
    "flight.sep": " · ",
    "flight.arr": "Arrival",
    "flight.dep": "Departure",
    "flight.noneShort": "Not provided — optional.",
    "flight.noneLong": "Not provided — optional, for airport transfers.",
    "step1.eyebrow": "Step 01",
    "step1.title": "Let’s get acquainted",
    "step1.docsLang": "In which language would you like to receive your documents?",
    "step1.docsLangSub": "Dans quelle langue souhaitez-vous recevoir vos documents ?",
    "step1.spoken": "What languages do you speak?",
    "step1.spokenSub": "Quelles langues parlez-vous ?",
    "step1.guide": "For guided visits, what language do you prefer?",
    "step1.guideSub": "Pour vos visites guidées, quelle langue préférez-vous ?",
    "step1.guideHelp": "Depending on the regions visited, we’ll do our best to offer a guide in this language.",
    "step1.name": "Full name",
    "step1.email": "Email address",
    "step1.phone": "Phone / WhatsApp",
    "step1.contactPref": "How would you like to be contacted?",
  },
  es: {
    "progress.1": "Paso 1 de 7 — Sus datos",
    "progress.2": "Paso 2 de 7 — Su viaje",
    "progress.3": "Paso 3 de 7 — Presupuesto y alojamiento",
    "progress.4": "Paso 4 de 7 — Experiencias e intereses",
    "progress.5": "Paso 5 de 7 — Salud y logística",
    "progress.6": "Paso 6 de 7 — Toque final",
    "progress.7": "Paso 7 de 7 — Sus vuelos internacionales",
    "progress.review": "Revisión — compruebe sus respuestas",
    "progress.done": "¡Gracias!",
    "header.title": "Cuéntenos el viaje de sus sueños",
    "header.sub": "Algunas preguntas para crear una experiencia a su medida. Unos 4 minutos.",
    "nav.prev": "← Anterior",
    "nav.next": "Siguiente →",
    "nav.recap": "Ver resumen",
    "nav.editReview": "← Editar",
    "nav.submit": "Confirmar y enviar ✨",
    "nav.sending": "Enviando…",
    "review.title": "Resumen",
    "review.contact": "Datos de contacto",
    "review.trip": "Viaje",
    "review.budget": "Presupuesto y alojamiento",
    "review.exp": "Experiencias",
    "review.health": "Salud y logística",
    "review.final": "Toque final",
    "review.flights": "Vuelos internacionales",
    "review.edit": "Editar",
    "done.line1": "Su concierge preparará algo excepcional para usted. 🇨🇴",
    "done.line2": "🕐 Respuesta en 24–48 h",
    "errors.fields": "Revise los campos marcados.",
    "errors.submitIncomplete": "Algunas respuestas están incompletas. Vuelva a los pasos indicados.",
    "errors.submitFailed": "No se pudo enviar. Inténtelo de nuevo.",
    "errors.network": "Red no disponible.",
    "done.title": "¡Gracias, {name}!",
    "review.tripLine": "{n} viajeros, {d} días",
    "flight.sep": " · ",
    "flight.arr": "Llegada",
    "flight.dep": "Salida",
    "flight.noneShort": "Sin datos — opcional.",
    "flight.noneLong": "Sin datos — opcional, para traslados al aeropuerto.",
    "step1.eyebrow": "Paso 01",
    "step1.title": "Conozcámonos",
    "step1.docsLang": "¿En qué idioma desea recibir sus documentos?",
    "step1.docsLangSub": "In which language would you like to receive your documents?",
    "step1.spoken": "¿Qué idiomas habla?",
    "step1.spokenSub": "What languages do you speak?",
    "step1.guide": "Para visitas guiadas, ¿qué idioma prefiere?",
    "step1.guideSub": "For guided visits, what language do you prefer?",
    "step1.guideHelp": "Según las regiones visitadas, haremos lo posible por ofrecerle un guía en ese idioma.",
    "step1.name": "Nombre completo",
    "step1.email": "Correo electrónico",
    "step1.phone": "Teléfono / WhatsApp",
    "step1.contactPref": "¿Cómo prefiere que le contactemos?",
  },
  de: {
    "progress.1": "Schritt 1 von 7 — Ihre Angaben",
    "progress.2": "Schritt 2 von 7 — Ihre Reise",
    "progress.3": "Schritt 3 von 7 — Budget & Unterkunft",
    "progress.4": "Schritt 4 von 7 — Erlebnisse & Interessen",
    "progress.5": "Schritt 5 von 7 — Gesundheit & Logistik",
    "progress.6": "Schritt 6 von 7 — Letzte Details",
    "progress.7": "Schritt 7 von 7 — Ihre internationalen Flüge",
    "progress.review": "Überprüfung — bitte prüfen Sie Ihre Angaben",
    "progress.done": "Danke!",
    "header.title": "Erzählen Sie uns von Ihrer Traumreise",
    "header.sub": "Ein paar Fragen für ein Erlebnis nach Maß. Etwa 4 Minuten.",
    "nav.prev": "← Zurück",
    "nav.next": "Weiter →",
    "nav.recap": "Zur Übersicht",
    "nav.editReview": "← Bearbeiten",
    "nav.submit": "Bestätigen und senden ✨",
    "nav.sending": "Wird gesendet…",
    "review.title": "Übersicht",
    "review.contact": "Kontaktdaten",
    "review.trip": "Reise",
    "review.budget": "Budget & Unterkunft",
    "review.exp": "Erlebnisse",
    "review.health": "Gesundheit & Logistik",
    "review.final": "Letzte Details",
    "review.flights": "Internationale Flüge",
    "review.edit": "Bearbeiten",
    "done.line1": "Ihr Concierge bereitet etwas Außergewöhnliches für Sie vor. 🇨🇴",
    "done.line2": "🕐 Antwort innerhalb von 24–48 Std.",
    "errors.fields": "Bitte prüfen Sie die markierten Felder.",
    "errors.submitIncomplete": "Einige Antworten sind unvollständig. Bitte die betreffenden Schritte prüfen.",
    "errors.submitFailed": "Senden fehlgeschlagen. Bitte erneut versuchen.",
    "errors.network": "Netzwerk nicht verfügbar.",
    "done.title": "Danke, {name}!",
    "review.tripLine": "{n} Reisende, {d} Tage",
    "flight.sep": " · ",
    "flight.arr": "Ankunft",
    "flight.dep": "Abflug",
    "flight.noneShort": "Keine Angabe — optional.",
    "flight.noneLong": "Keine Angabe — optional, für Flughafentransfers.",
    "step1.eyebrow": "Schritt 01",
    "step1.title": "Lernen wir uns kennen",
    "step1.docsLang": "In welcher Sprache möchten Sie Ihre Dokumente erhalten?",
    "step1.docsLangSub": "In which language would you like to receive your documents?",
    "step1.spoken": "Welche Sprachen sprechen Sie?",
    "step1.spokenSub": "What languages do you speak?",
    "step1.guide": "Welche Sprache bevorzugen Sie für Führungen?",
    "step1.guideSub": "For guided visits, what language do you prefer?",
    "step1.guideHelp": "Je nach Region tun wir unser Möglichkeiten, einen Guide in dieser Sprache anzubieten.",
    "step1.name": "Vollständiger Name",
    "step1.email": "E-Mail-Adresse",
    "step1.phone": "Telefon / WhatsApp",
    "step1.contactPref": "Wie möchten Sie kontaktiert werden?",
  },
};

export function intakeT(lang: IntakeLang, key: string): string {
  return STRINGS[lang][key] ?? STRINGS.fr[key] ?? key;
}

export function progressLabelForStep(lang: IntakeLang, uiStep: number): string {
  return intakeT(lang, `progress.${uiStep}` as const);
}

type Step7 = z.infer<typeof intakeFullSchema>["step7"];

export function formatIntakeFlightReview(lang: IntakeLang, step7: Partial<Step7> | undefined): string {
  const sep = intakeT(lang, "flight.sep");
  const parts: string[] = [];
  const aa = step7?.arrivalAirline?.trim();
  const an = step7?.arrivalFlightNumber?.trim();
  const adt = step7?.arrivalDate?.trim();
  if (aa || an || adt) {
    parts.push(
      `${intakeT(lang, "flight.arr")}: ${[aa, an, adt, step7?.arrivalTime?.trim()].filter(Boolean).join(sep)} → ${step7?.arrivalCity?.trim() || "Bogotá"}`,
    );
  }
  const da = step7?.departureAirline?.trim();
  const dn = step7?.departureFlightNumber?.trim();
  const ddt = step7?.departureDate?.trim();
  if (da || dn || ddt) {
    parts.push(
      `${intakeT(lang, "flight.dep")}: ${step7?.departureCity?.trim() || "Bogotá"}${sep}${[da, dn, ddt, step7?.departureTime?.trim()].filter(Boolean).join(sep)}`,
    );
  }
  if (parts.length === 0) return intakeT(lang, "flight.noneLong");
  return parts.join(" | ");
}
